function ok = bins_equal(a, b)
    ok = height(a) == height(b) && ...
         all(a.score_min == b.score_min) && ...
         all(a.score_max == b.score_max) && ...
         all(a.n_obs     == b.n_obs) && ...
         all(a.n_bads    == b.n_bads);
end
