function bins = load_bins(fixtures_dir, filename)
    t = read_csv_table(fullfile(fixtures_dir, filename));
    bins = table( ...
        double(t.score_min), ...
        double(t.score_max), ...
        double(t.n_obs), ...
        double(t.n_bads), ...
        'VariableNames', {'score_min', 'score_max', 'n_obs', 'n_bads'});
    if any(strcmp(t.Properties.VariableNames, 'pd'))
        bins.pd = double(t.pd);
    end
end
