function merged = merge_bins(a, b)
% MERGE_BINS  Merge two adjacent bins into one spanning their combined range.
%
%   merged = MERGE_BINS(a, b)
%
%   a, b   — single-row bin tables (score_min, score_max, n_obs, n_bads)
%   merged — single-row bin table with combined counts

merged = table( ...
    a.score_min, ...
    b.score_max, ...
    a.n_obs + b.n_obs, ...
    a.n_bads + b.n_bads, ...
    'VariableNames', {'score_min', 'score_max', 'n_obs', 'n_bads'});
end
