function ok = weighted_bins_equal(a, b, tol)
    if nargin < 3; tol = 1e-6; end
    if height(a) ~= height(b); ok = false; return; end
    ok = all(a.score_min == b.score_min) && ...
         all(a.score_max == b.score_max) && ...
         all(abs(a.n_obs - b.n_obs) < tol) && ...
         all(abs(a.n_bads - b.n_bads) < tol) && ...
         all(a.count == b.count) && ...
         all(a.count_bads == b.count_bads);
end
